name: Caddy Manager CI build
run-name: ${{ gitea.actor }} is running CI pipeline
on:
  push:
    branches:
      - main

jobs:
  docker:
    env:
      RUNNER_TOOL_CACHE: /toolcache
      NUGET_PACKAGES: ${{ gitea.workspace }}/.nuget/packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Gitea
        uses: docker/login-action@v3
        with:
          registry: http://${{ vars.DOCKER_GITEA_DOMAIN }}
          username: ${{ vars.DOCKER_GITEA_USERNAME }}
          password: ${{ secrets.DOCKER_GITEA_PAT }}
          config-inline: |
            [registry."${{ vars.DOCKER_GITEA_DOMAIN }}"]
              http = true
              insecure = true            
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9' # SDK Version to use.
          dotnet-quality: 'ga'
          cache: true
      - name: Restore dependencies 
        run: dotnet restore --locked-mode
      - name: Build solution  
        run: dotnet build --configuration Release --no-restore
      - name: Publish container
        run: |
          dotnet publish \
          --configuration Release --os linux --arch x64 \
          /t:PublishContainer -p ContainerRegistry=${{ vars.DOCKER_GITEA_DOMAIN }}